FROM alpine:3

ARG TARGETPLATFORM
ARG BINARY_NAME

# Install certificates and timezone data
RUN apk add --no-cache ca-certificates tzdata

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the Pre-built binary file from GoReleaser
COPY $TARGETPLATFORM/$BINARY_NAME ./app

# Copy translation files for internationalization support
COPY i18n/locales ./i18n/locales

# Command to run the executable
ENTRYPOINT ["/app/app"]
